### ISSUE TITLE
"Live Reload is not possible as body or head tag or defined tag is missing in HTML" warning shows on every reload

### ISSUE THREAD

**Issue by skelesp** [ritwickdey/vscode-live-server#22]
Every time I save a watched file, my page reloads, but in VS code the warning appears "Live Reload is not possible as body or head tag or defined tag is missing in HTML". I have to close the warning every time (very annoying) and there is no option to disable this warning.

**Comment by ritwickdey** [comment]
okay! It's added in new version. Add <body> or <head> tag in html. It will disappear.

**Comment by ritwickdey** [comment]
Without <body> or <head> tag live reload is not possible.

**Comment by ritwickdey** [comment]
Have you meant that? or I am getting wrong point?

**Comment by skelesp** [comment]
1) I don't understand the current behaviour, because the warning is saying that live reload won't work, but it is working... So, I think the warning comes at the wrong time (or I don't fully understand the purpose of the warning :-) ).

2) If this tag-problem occurs, I think it's better to show the warning only once in VS code and not on every save. And it might be better to show the warning in the console.

**Comment by ritwickdey** [comment]
Okay! I understand. And definitely as I always give priority on feedback, I am adding a settings so that we can turn off the warring message.

And If it is bug, can you tell me that what platform you are using? and please give a try as follow : ->

1. Make a new folder
2. Create a new HTML file.
3. Open the folder to VSCODE
4. type exclamation sign (!) and tab. (Emmet Snippet)
5. Start Live Server. 

And now please tell me, is this working? or you're still getting the warning?.

**Comment by ritwickdey** [comment]
I want to know if it is a bug or not before releasing new version. Because it is working on my Windows 10

**Comment by skelesp** [comment]
It is working (without a warning) when I create a new file in new folder. So there must be something wrong in my file?

The structure of my file is :
<!DOCTYPE html>
<html ng-app="TestApp">
	<head>
        </head>
        <body ng-controller="testCtrl">
        </body>
</html>

So I think there shouldn't be a warning, because I have head and body tags?

(I'm also working in windows 10)

**Comment by ritwickdey** [comment]
Is this not working for you?........ I tried....
```html
<!DOCTYPE html>
<html ng-app="TestApp">
	<head>
        </head>
        <body ng-controller="testCtrl">
        </body>
</html>
```


but it is working for me....

**Comment by skelesp** [comment]
yes, it works if I try it with that simple structure, but with my complete code, it is still showing the warning.

Does it matter which code is between the head and body tags? I would expect that the existence of head/body-tags is enough? But apparently, some of my code between the head-tags or the body-tags is triggering that warning...

**Comment by ritwickdey** [comment]
This issue has been fixed with v2.1.1 update. Please update it from vscode marketplace 😄.

If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).

**Comment by irakliykech** [comment]
Hello. Sorry for request, but I have same problem with LiveServer. When I create new document, type (!) and tab, VSCode create base html structur automaticly. But if i add some tags in <head> or <body>, than LiveReload warning than "Live Reload is not possible without body or head tag."

**Comment by martonberecz** [comment]
Same issue here. As per above.

**Comment by jonwow** [comment]
> Same issue here. As per above.

I think I found a solution - try creating the html file in the file explorer instead of powershell/terminal.

**Comment by meberg** [comment]
I had the same problem. I just "solved" it by pressing 'I understand - don't show again'.

**Comment by gordwelling** [comment]
> I had the same problem. I just "solved" it by pressing 'I understand - don't show again'.

I had the same problem and tried the same step to 'Don't show again'.  I had to reload the page in the browser and then make a change to the html file and save it in VSCode.

**Comment by ChrisColeTech** [comment]
My HTML has body and head tag, and I am still getting the message ...

**Comment by Mada75** [comment]
I have just had the same problem having not had an issue for 12+ months. 
A new .html file with exactly the same content would work so slightly confused. Ended up deleting my index.html and creating a new one then pasting the content over and it worked.
As a side note - my original .html file was created in the terminal and my "working" .html created in VSC as referenced above.
Strange one.

**Comment by Ace-Cassidy** [comment]
Also having this problem

[index (copy).html.txt](https://github.com/ritwickdey/vscode-live-server/files/4073678/index.copy.html.txt)

**Comment by vpopescu** [comment]
I've seen issues with the file encoding (UTF-16 has caused it to complain about HEAD or BODY missing)

**Comment by Tronic** [comment]
I'm working with HTML5 which doesn't need these tags, and should have Live Server's snippet simply appended to the end of the document. Could you change the extension so that if `body` is not found, it just adds its code to the end and doesn't give this warning?

**Comment by alfken** [comment]
I believe this _might_ be a problem with the extension "Browser Preview" at  https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview. But I admit it is just a guess - I have not dug deep into it.
One way to see if my hunch is right, would be to investigate if this issue ever occurs when the Live Server extension setting "Use Browser Preview" is unchecked.

**Comment by mrmatata** [comment]
it happened to me too and it was very irritating so i turned it off from settings.json

"liveServer.settings.donotVerifyTags": off,

**Comment by Tronic** [comment]
> it happened to me too and it was very irritating so i turned it off from settings.json
> 
> "liveServer.settings.donotVerifyTags": off,

How did you get this working? It would appear that this takes `true` or `false` rather than `off` but I couldn't get rid of the warning or get live reloads working with any value.

**Comment by mrmatata** [comment]
> > it happened to me too and it was very irritating so i turned it off from settings.json
> > "liveServer.settings.donotVerifyTags": off,
> 
> How did you get this working? It would appear that this takes `true` or `false` rather than `off` but I couldn't get rid of the warning or get live reloads working with any value.

i think this did it for me
"liveServer.settings.donotShowInfoMsg": true,
"liveServer.settings.donotVerifyTags":true,

**Comment by Tronic** [comment]
@mrmatata That gets rid of the message but auto reloading still doesn't work unless there is `</body>` in the document (no other tags are needed).

**Comment by ryancbolton** [comment]
> I had the same problem. I just "solved" it by pressing 'I understand - don't show again'.

This somehow fixed it for me a s well, btw I know this is old but still happening in version 5.6.1

**Comment by christianwhite009** [comment]
Hey everyone, so today I got the live server to work by downloading an older version (v 1.0) and it worked so far. I'm not getting that dreaded live server needs a head or body tag message and more importantly my webpage reloads without me having to hit ctrl + R (or F5). I haven't received any issues, you can give a try and let me know

**Comment by christianwhite009** [comment]
For anyone downloading an older version, please note that you'll have to make consistent changes for the web page to refresh by itself. In other, words if you take a break from coding you'll probably have to refresh the page a couple times after making a change, usually I have to manually refresh 3 times before live server works.

**Comment by Amosi-04-sanga** [comment]
the same to me

**Comment by phoenixeliot** [comment]
I find that I get this erroneous message if I have an invalid import in a CSS file that is imported by the CSS file imported in my HTML.

In particular, a line was trying to import a folder, and one was trying to import by name without `.css`, and fixing/removing those removed the warning message:
```
@import url(../blocks/footer/__columns/_content/);
@import url(../blocks/header/__square-pic/header__square-pic);
```

**Comment by nanyou225** [comment]
why the {% load static %} tag 
is still displayed in my html page?

**Comment by Casonyx** [comment]
Idk guys but I got this error too.
So I got it when fixed my webpack.config. Lol. I didn't notice that my loader has two svg handlers. I fixed it and the error disappeared.

**Comment by mel-inda** [comment]
helloo, i received this error message today every time i reload my live server. i have both head tags and body tags so this issue is still happening today it seems.-.

**Comment by roke741** [comment]
Hello, I also had the error, but I think I solved it, simply add the <head><head> tag and in the extension settings, look for Live Server>Settings: Custom Browser, in my case select microsoft edge, because it is the that I usually use to observe the changes, and finally restart VS code, with that I solve the problem, I hope it works for you

**Comment by neospud1** [comment]
I solved it by changing the html file's encoding in the VSCode.
Click current encoding
![image](https://user-images.githubusercontent.com/5056971/163231561-f534a730-358b-4e11-b590-f44bdb4b1858.png)
Click save with encoding
![image](https://user-images.githubusercontent.com/5056971/163231692-e15f0185-abf5-4499-a089-83dfc3b4dd2a.png)
Click UTF-8
![image](https://user-images.githubusercontent.com/5056971/163231751-d5d48ca1-728b-4f79-9611-888593a2eaf4.png)

**Comment by chillgiova** [comment]
I had this problem randomly appeared after 1 year. I finally solved it, it was and @import row in the style.css file. This was the specific row: `@import 'https://fonts.googleapis.com/css?family=Montserrat:300, 400, 700&display=swap';`

**Comment by Ramjius** [comment]
It is because you have made a media query on your file and your display screen/window is in that size, and since you don't have a body or head in your media query----That's why!!! Had a similar case, try resizing your window, save and see.

**Comment by nafismahamudshahin** [comment]
![Screenshot_4](https://github.com/ritwickdey/vscode-live-server/assets/104847010/10219a6f-715c-44f8-ac2b-8989aabb4be2)
This is my problem please help me

**Comment by wegaro** [comment]
Same problem as above right now, my structure has head and body tag, so I don't know what it refers too. Any ideas?

**Comment by overholted** [comment]
I had this problem, too. I opened my .scss file, saved it and my extension recompiled the CSS. The pop-up is now gone.

**Comment by Sarveshreg** [comment]
Make sure that your HTML tab is active, not the CSS or JS!

**Comment by justingolden21** [comment]
Same issue as above. I previously never had this issue. It's a simple html file:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Project</title>
  </head>
  <body>
    hello
  </body>
</html>
```

![image](https://github.com/ritwickdey/vscode-live-server/assets/30274440/eb8c64f8-0d98-4978-baec-548d098a09ee)


It's a syntactically valid HTML file with head and body tag, and it serves other html files in the directory fine. The HTML tab is active and works when I open it without live server.

**Comment by WeaponXiii** [comment]
@justingolden21 it might be the utf-16 LE encoding issue. I created the file using ps7 prompt using Out-File cmdlet. Never had this issue crating empty file from command prompt though. Check these answer by @neospud1

> I solved it by changing the html file's encoding in the VSCode. Click current encoding ![image](https://user-images.githubusercontent.com/5056971/163231561-f534a730-358b-4e11-b590-f44bdb4b1858.png) Click save with encoding ![image](https://user-images.githubusercontent.com/5056971/163231692-e15f0185-abf5-4499-a089-83dfc3b4dd2a.png) Click UTF-8 ![image](https://user-images.githubusercontent.com/5056971/163231751-d5d48ca1-728b-4f79-9611-888593a2eaf4.png)

**Comment by yeon-dong** [comment]
I had the same problem with live-server.
When I turned on live-server by pressing the Go Live button and modified index.html and saved it, an error message saying "live reload is not possible without a head or body tag" appeared and the Chrome browser turned white.
I thought it was because I didn't turn on live-server in the direct folder,
and it turned out to be the same problem.
I'll attach a screenshot of the folder structure.
Please try opening the folder that contains the index.html file in vscode!
##Good Case
![image](https://github.com/user-attachments/assets/b2be6c4a-0b44-4c78-bd45-8bb243d9a2c6)
##Bad Case
![image](https://github.com/user-attachments/assets/90aceeef-909b-42c6-8b8d-c87f5bb4a017)

**Comment by martigej** [comment]
This bug was not fixed yet?
I have the warning "Live Reload is not possible as body or head tag or defined tag is missing in HTML" if in my <head> I have included JQuery:
<script src="https://code.jquery.com/jquery-1.10.2.js"></script> 
Removing this line the warning do not appear anymmore.

**Comment by desaroger** [comment]
I had the same problem with a very simple html and the reason was the encoding. Thanks @WeaponXiii !!

> @justingolden21 it might be the utf-16 LE encoding issue. I created the file using ps7 prompt using Out-File cmdlet. Never had this issue crating empty file from command prompt though. Check these answer by @neospud1
> 
> > I solved it by changing the html file's encoding in the VSCode. Click current encoding ![image](https://user-images.githubusercontent.com/5056971/163231561-f534a730-358b-4e11-b590-f44bdb4b1858.png) Click save with encoding ![image](https://user-images.githubusercontent.com/5056971/163231692-e15f0185-abf5-4499-a089-83dfc3b4dd2a.png) Click UTF-8 ![image](https://user-images.githubusercontent.com/5056971/163231751-d5d48ca1-728b-4f79-9611-888593a2eaf4.png)

**Comment by ScottBeeson** [comment]
I'm having this same issue. It's not encoding. The HTML file is in the root of the project and is named Index.html. I have the index.html file selected when clicking "Go Live". It has a head and body tag. Here's the full HTML if it helps...

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MSAL Login Demo - Index</title>
    <script src="https://alcdn.msauth.net/browser/2.30.0/js/msal-browser.min.js"></script>
    <script src="auth.js"></script>
    <script src="common.js"></script>
    <link rel="stylesheet" href="main.css">
</head>

<body>
    <div id="menuContainer"></div>
    <div id="mainContent">
        <h1>Index Page</h1>
        <div id="user-info">Checking login...</div>
    </div>
    <script>
        window.onload = function () {
            checkLogin();
            loadMenu("Home");
        };
    </script>
</body>

</html>
```

**Comment by AndrewElans** [comment]
Live Server extension depends on the [github.com/tapio/live-server](https://github.com/tapio/live-server) package. 

In short: `params` are sent from Live Server to live-server. `params` includes callback that shows message `Live Reload is not possible without a head or body tag.` If your code imports any file with extension `"", ".html", ".htm", ".xhtml", ".php", ".svg"` and the file does not have any of the tags `</body>, </svg>, </head>`, the message is shown. 

If you are annoyed with this message: open Live Server extension source code in vscode (on Windows C:\Users\your-user\.vscode\extensions\ritwickdey.liveserver-5.7.9\.vscode) -> file `appModel.js` -> change:

```javascript
// from
let params = Helper_1.Helper.generateParams(pathInfos.rootPath, workspacePath, () => {
    this.tagMissedCallback();
});

// to empty callback
let params = Helper_1.Helper.generateParams(pathInfos.rootPath, workspacePath, () => {});

// or to this if you want to log this message instead of seeing a popup
// before "class AppModel {" add
const out = vscode_1.window.createOutputChannel("Live Server 5.7.9");
// change params to 
let params = Helper_1.Helper.generateParams(pathInfos.rootPath, workspacePath, () => {
    out.appendLine('Live Reload is not possible without a head or body tag.');
});

```

![Image](https://github.com/user-attachments/assets/1af307ef-a08b-4320-a2ae-85850f38b7fe)

All logic based on these excerpts:
```javascript
// ==========================
// in Live Server appModel.js

class AppModel {
    // ...
    tagMissedCallback() {
        this.showPopUpMsg('Live Reload is not possible without a head or body tag.', null, true);
    }
    Golive(pathUri) {
        // ...
        let params = Helper_1.Helper.generateParams(pathInfos.rootPath, workspacePath, () => {
            this.tagMissedCallback();
        });
        LiveServerHelper_1.LiveServerHelper.StartServer(params, ...)
        // ...
    }
    // ...
};    

// ==========================
// in Live Server LiveServerHelper.js
let ServerInstance = require('live-server').start(params); 

// ==========================
// in live-server index.js
function staticServer(root, onTagMissedCallback) {
    return function (req, res, next) {
        // ...
        var injectCandidates = [
            new RegExp("</body>", "i"),
            new RegExp("</svg>"),
            new RegExp("</head>", "i")
        ];

        function file(filepath /*, stat*/) {
            var x = path.extname(filepath).toLocaleLowerCase(), match, possibleExtensions = ["", ".html", ".htm", ".xhtml", ".php", ".svg"];
            // ...
            var contents = fs.readFileSync(filepath, "utf8");
            for (var i = 0; i < injectCandidates.length; ++i) {
                match = injectCandidates[i].exec(contents);
                if (match) {
                    injectTag = match[0];
                    break;
                }
            }
            if (!injectTag && onTagMissedCallback) {
                onTagMissedCallback();
            }
            // ...
        }
    } 
}

```

**Comment by jeFFu369** [comment]
> This bug was not fixed yet? I have the warning "Live Reload is not possible as body or head tag or defined tag is missing in HTML" if in my I have included JQuery:
> 
> <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
> Removing this line the warning do not appear anymmore.

Its best that u download and use jquery locally, try and see
