### ISSUE TITLE
command 'extension.liveServer.goOnline' not found

### ISSUE THREAD

**Issue by ann-maier** [ritwickdey/vscode-live-server#78]
Hello, I have a problem with opening live server. It worked perfectly month ago, but now when I try to do it I have a warn/error (if I use command palette) message:

> command 'extension.liveServer.goOnline' not found

![untitled](https://user-images.githubusercontent.com/29557221/36088542-599a3750-0fe0-11e8-9c8b-0536be302a7b.png)

I have tried to uninstall/install it again, but it does nothing.

**Comment by ann-maier** [comment]
I have tried to uninstall/install it again, but it does nothing.

**Comment by ritwickdey** [comment]
I'm not sure, why it's happening! 

This is same as https://github.com/ritwickdey/vscode-live-server/issues/75

Work-around :

**Comment by ritwickdey** [comment]
I'm not sure, why it's happening!

This is same as #75

Work-around : `C:\Users\Anna\.vscode\extensions\`
and Delete the folder `ritwickdey.liveserver-3.2.0`

and install Live Server again.

#75

**Comment by ann-maier** [comment]
Finally worked, thanks a lot!

**Comment by ritwickdey** [comment]
Seriously I don't know why it's happening. 
It may an issue of vscode while upgrading extension. 
I'm thinking to redeploy it.



Anyway, thanks for the report & the confirmation ! 

If you really like the extension, please drop a review in vscode marketplace.
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by alebarbaja** [comment]
I had the same problem, which was fixed by deleting the folder and reinstalling Live Server. Just for you know it.

**Comment by joeEscob1023** [comment]
Idk if this is an issue for other people since its been 2 month since this post, but the same issue happened to me today, but i followed your steps and reinstalled it and it works again.

**Comment by diane1perez** [comment]
I am having the same problem live server don't work it says to download github and downloaded it and it still don't work

**Comment by rjoydip** [comment]
Have you installed liveserver before?

**Comment by diane1perez** [comment]
no i have not new at this just learning    On Saturday, June 16, 2018, 5:42:35 PM PDT, Joydip Roy <notifications@github.com> wrote:  
 
 
Have you installed liveserver before?

**Comment by NickFoden** [comment]
I found small issue where if I open vs code and start new index.html file there is no shortcut and vscode has purple bottom border, and then if I go to open and open folder containing index.html file then i see vscode bottom border is blue and clicking on index.html then I have shortcut to live server in vs code bottom border. I wonder if previous issues above are same thing where the user is not in a folder and just on a standalone file ?

**Comment by rjoydip** [comment]
@NickFoden  This is Strange. Can you provide some screenshot?

**Comment by NickFoden** [comment]
Sure here is if I open empty VSCode and start new index.html file and have saved it. 

![just file open](https://user-images.githubusercontent.com/8321838/43545284-7b78ab74-95a3-11e8-9e00-f62438749948.png)

And then here is if I open parent folder of the index.html file. Now has live server shortcut and window is blue border. 

![with folder open](https://user-images.githubusercontent.com/8321838/43545285-7b86d58c-95a3-11e8-9c34-113661f18712.png)

**Comment by dipadana** [comment]
@NickFoden thank you for the tutorial. I love this extension!

**Comment by Archiveagain** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\`
> and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

The same problem happend to me, but fortunately quickly solved by delete live server from folder and reinstall. Cheers !!!

**Comment by IrvinIS** [comment]
I`ve tried the ways offered earlier but it still doesn`t work. Anybody could help me to fix the Live Server and make it work?

**Comment by maks1981** [comment]
Guys hello, i have the same problem but i could not solve it.
When i press Open with live server below message appears "Open a folder or workspace... (File -> Open Folder)", I opened any html file there many times but nothing about live server works ,guys how can i solve this?please any help
Kind Regards

**Comment by maks1981** [comment]
> > I'm not sure, why it's happening!
> > This is same as #75
> > Work-around : `C:\Users\Anna\.vscode\extensions\`
> > and Delete the folder `ritwickdey.liveserver-3.2.0`
> > and install Live Server again.
> 
> The same problem happend to me, but fortunately quickly solved by delete live server from folder and reinstall. Cheers !!!

Are you using Mac? if so where is that folder to delete and reinstall ?

**Comment by lramac3** [comment]
I use mac. Initially Go Live was not showing on the bottom of my VSCode. I right clicked on the html file and clicked Open with Live Server. It gave me an error the folder is not open in VSCode. I just had to open the folder in VS Code and navigate to the html file. When I clicked on Open with Live Server again, it worked.

**Comment by IrvinIS** [comment]
> I`ve tried the ways offered earlier but it still doesn`t work. Anybody could help me to fix the Live Server and make it work?

I`ve found how to fix an issue. If you can`t see the "Go Live" button you should open the folder your files in VS Code workplace, then it should work. Hope it would help

**Comment by dbooyah93** [comment]
Happens to me on occasion and the "go live" button comes back intermittently. The new thing i did before this happened is that i opened live share and played with the terminal. I am brand new to learning JavaScript and I don't do much but very basic things, and I do not use any other extensions besides the live share and live server.

**Comment by patelrohan750** [comment]
Server is started at 5500 but failed to open in Browser Preview. Got Browser Preview extension installed?

**Comment by jamillaclemons** [comment]
Hello.  I'm new to this.  I've read a lot of the other posts and implemented some of the advice......  I'm having a problem with live server.   I've deleted the javaScript file, and uninstalled live server a couple of times, and started from scratch, but when I open the file in live server and right click.  I don't get the option to "inspect."  I only get 3 options:   

1. Reload page
2. Save page as
3. Print page

Am I doing anything wrong?


Please give me some advice.  I've spent a lot of time trying to figure this out.  I'd like to move forward.

**Comment by Hello-Chen** [comment]
I ran Go Live to display not found and tried to delete the plug-in folder and download it again, but it still failed. I used vscode insiders version 1.4.3. I hope it can be solved.

**Comment by shivani9H** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\`
> and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

i am having same problem unable to find go live!

**Comment by shivani9H** [comment]
Command 'Live Server: Open with Live Server' resulted in an error (command 'extension.liveServer.goOnline' not found) 
this is what its showing!

**Comment by diane1perez** [comment]
Sent from Yahoo Mail on Android 
 
  On Sat, Apr 25, 2020 at 5:21 PM, shivani9H<notifications@github.com> wrote:   


Command 'Live Server: Open with Live Server' resulted in an error (command 'extension.liveServer.goOnline' not found)
this is what its showing!

**Comment by Michal-sw** [comment]
Had the same problem, reinstalling didn't help, however reloading my browser solved everything.

**Comment by Eeshal-I** [comment]
> Hello, I have a problem with opening live server. It worked perfectly month ago, but now when I try to do it I have a warn/error (if I use command palette) message:
> 
> > command 'extension.liveServer.goOnline' not found
> 
> ![untitled](https://user-images.githubusercontent.com/29557221/36088542-599a3750-0fe0-11e8-9c8b-0536be302a7b.png)
> 
> I have tried to uninstall/install it again, but it does nothing.

**Comment by bassamanator** [comment]
Same issue here on linux (Manjaro).

**Comment by madd-project** [comment]
**In My Case It Goes Like -** It Works finely on 1st install of VS Code then the after 2 days It Started Giving `extension.liveServer.goOnline` Error. Then I reinstalled VSCode and then It Worked Fine For one time and When after Sometime it Again Gave me Error... It Really Hurt. 

And I also Tried #75 and #78 But It's Not Working. Please Help .. I have Some IMP stuffs to be Run

**Comment by azizthedev** [comment]
> I use mac. Initially Go Live was not showing on the bottom of my VSCode. I right clicked on the html file and clicked Open with Live Server. It gave me an error the folder is not open in VSCode. I just had to open the folder in VS Code and navigate to the html file. When I clicked on Open with Live Server again, it worked.

Yes I'm using Windows and I did exactly like you told it and it worked. Turns out the folder containing the file has to be opened .

**Comment by ZarifaMammadzada** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\`
> and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

Thank you so much , its really working

**Comment by PuLeE-PuLendrA** [comment]
live server doesn't working....having an issue #780

**Comment by eltx** [comment]
> I use mac. Initially Go Live was not showing on the bottom of my VSCode. I right clicked on the html file and clicked Open with Live Server. It gave me an error the folder is not open in VSCode. I just had to open the folder in VS Code and navigate to the html file. When I clicked on Open with Live Server again, it worked.

Yes, I am macOS as well. Following your instruction, it is worked now. Thank you.

**Comment by XxSDxX** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\`
> and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.
Yo bro!  Thanks for the help!

it work now

**Comment by githubbilli** [comment]
Yea im facing the same problem as well. When i click go live it says _"command 'extension.liveServer.goOnline' not found"_.

**Comment by Shivamkumarbrh** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\` and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

Now my vs code live server work.
thanks for suggestion.

**Comment by spragginsdesigns** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\` and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

This worked! Thank you so much. I needed this. Reinstalling VS Code didn't even fix it and I use it every day.

**Comment by digitarald** [comment]
@ritwickdey do you know if this is still an issue in recent?

To everybody who sees this issue while debugging the same problem, please 👍 this comment and use the command `Help: Report Issue` to file an issue in the vscode repo so we can get some more information.

**Comment by Sammeeey** [comment]
> I'm not sure, why it's happening!
> 
> This is same as #75
> 
> Work-around : `C:\Users\Anna\.vscode\extensions\` and Delete the folder `ritwickdey.liveserver-3.2.0`
> 
> and install Live Server again.

You may want to
1. uninstall
2. close VSCode
3. delete the folder
4. restart VSCode
5. install extension again
✌

**Comment by Ne15inh0** [comment]
Olá , como faço para resolver esse problema, já desinstalei e instalei diversas vezes e continua me apresentando isso?

"Esta página não está funcionandoNenhum dado foi enviado por 127.0.0.1
ERR_EMPTY_RESPONSE "

**Comment by sivelswhy** [comment]
@Ne15inh0 please keep an english chat

**Comment by aiintimaetedegree** [comment]
هناك خطأ تنسيق

**Comment by aiintimaetedegree** [comment]
هناك خطأ سأرجع إلى صفحة المستند intimate.degree.card@gmail.com

**Comment by purchaselocally** [comment]
None of these tricks helped. 
I am trying to work with v5.7.9.
Please help. <3 
Thank you.

Server says it is started. No window opens. 

If there is a way to reset all settings on VS Code, I would like to try that. I have deleted users, uninstalled VS Code. Deleted all VS code files from computer. When I reinstall, all settings except extensions stay the same. When I download an extension, all settings are the same from before I deleted the VS code program. I have downloaded VS Code extension in Chrome. I have ensure the browsers are set for the computer and VS code as the same default browsers (chrome). I have even deleted and factory reset my windows computer.

Thanks in advance.

**Comment by dbooyah93** [comment]
The PATH isn't set correctly.

**Comment by purchaselocally** [comment]
What should it be?

**Comment by vinod-kumar1** [comment]
whats the solution for MAC users?

**Comment by dbooyah93** [comment]
> whats the solution for MAC users?

Switch to Linux

**Comment by BlazeDu** [comment]
On Mac, in the terminal, use the `fzf` command to find all files related to `live server`, then delete them.
<img width="1470" alt="截屏2024-04-05 11 48 50" src="https://github.com/ritwickdey/vscode-live-server/assets/158279684/5adea515-9180-4cde-8b92-2f974c60b596">

**Comment by Ablailah** [comment]
im having problem with #751

**Comment by adeenaamir** [comment]
how is liveserver show

**Comment by Sebastian08112009** [comment]
tengo un problema diferente y es que cuando voy a abrir el html en el navegador  presionando open with live server me aparece en la parte de abajo port: 5500 y no se me abre el navegador. alguin sabe la solucion? si me entendieron y me pueden ayudar se los agradesco mucho.


<img width="1361" height="730" alt="Image" src="https://github.com/user-attachments/assets/e946dfbf-0a0b-4cc7-bc42-14ac73dc30ac" />

**Comment by faarizsheikh** [comment]
> tengo un problema diferente y es que cuando voy a abrir el html en el navegador presionando open with live server me aparece en la parte de abajo port: 5500 y no se me abre el navegador. alguin sabe la solucion? si me entendieron y me pueden ayudar se los agradesco mucho.
> 
> <img alt="Image" width="1361" height="730" src="https://private-user-images.githubusercontent.com/197981112/555656027-e946dfbf-0a0b-4cc7-bc42-14ac73dc30ac.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzU5NTEyMTYsIm5iZiI6MTc3NTk1MDkxNiwicGF0aCI6Ii8xOTc5ODExMTIvNTU1NjU2MDI3LWU5NDZkZmJmLTBhMGItNGNjNy1iYzQyLTE0YWM3M2RjMzBhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQxMVQyMzQxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDk4NmE3MzYzOGE1MDJiNWI4YzVhNGJmNDA3MzYxYWIyMTJlMDlkY2RiZDhjYjI5MzExMjZkMTg1YWRmYmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.s5ED39y8Dt-1tQ82bOTytesMTW47wyUTCkErvp1lP0c">

I don't speak the language you wrote the comment in, sorry.
